# Generated by Django 3.1.7 on 2022-12-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='privatekey1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='privatekey2',
            field=models.IntegerField(default=0),
        ),
    ]
