# Generated by Django 3.1.7 on 2022-12-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20221203_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='publickey1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='publickey2',
            field=models.IntegerField(default=0),
        ),
    ]
