# Generated by Django 3.1.7 on 2022-12-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20221204_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='privatekey1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='world',
            name='privatekey2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='world',
            name='publickey1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='world',
            name='publickey2',
            field=models.IntegerField(default=1),
        ),
    ]
